### ISSUE TITLE
Calculated heap size

### ISSUE THREAD

**Issue by hacfi** [vektorcloud/elasticsearch#1]
Really nice idea to have a calculated heap size fallback. After having recently experienced ES memory issues on a dedicated host (no docker..we had way too little heap size) I was wondering how you decide to give 90% to ES? General recommendation from Elastic is 50% (see https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html#_give_half_your_memory_to_lucene & https://www.elastic.co/guide/en/elasticsearch/guide/current/_limiting_memory_usage.html) but not sure if that also applies to running ES in Docker.

**Comment by bcicen** [comment]
Good point; I should probably document the automatic heap size calculation a bit better -- it's actually based on 90% of the _container_ memory limit(see [here](https://github.com/vektorlab/docker-elasticsearch/blob/master/entrypoint.sh#L5)). If the container is started without a memory limit, it will attempt to take 90% of all system memory.

**Comment by hacfi** [comment]
:+1: thanks for the reply..makes sense now!
